app.env=dev

# ??? DB ??
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=${DB_URL:jdbc:hsqldb:mem:testdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# ?? ????? ??? ?? ? ???
logging.level.egovframework=DEBUG
logging.level.org.springframework=INFO

# thymeleaf ?? ?? ??
spring.thymeleaf.cache=false
