spring.application.name=egovframe-project

# ?? ???
spring.profiles.active=dev

# ?? WAS ?? ? server.port? ? ??? ??? ??? ??
server.port=8080

# Bean override ??
spring.main.allow-bean-definition-overriding=true

# JPA
spring.jpa.open-in-view=false

# ?? ?? ??
logging.level.root=INFO
logging.level.egovframework=INFO
logging.level.org.springframework=INFO

# ???
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true