app.env=stg

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

logging.level.egovframework=INFO
logging.level.org.springframework=WARN

spring.thymeleaf.cache=true
