app.env=prod

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ?? ??? ?? ???? ??
logging.level.root=INFO
logging.level.egovframework=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

spring.thymeleaf.cache=true